//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabaBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenses
    {
        public int id_расхода { get; set; }
        public Nullable<int> id_кампании { get; set; }
        public string статья_расхода { get; set; }
        public Nullable<decimal> сумма { get; set; }
        public Nullable<System.DateTime> дата { get; set; }
    
        public virtual Campaigns Campaigns { get; set; }
    }
}
