//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabaBD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public int id_задачи { get; set; }
        public Nullable<int> id_кампании { get; set; }
        public string описание { get; set; }
        public Nullable<int> id_исполнителя { get; set; }
        public Nullable<System.DateTime> срок_выполнения { get; set; }
        public string статус { get; set; }
    
        public virtual Campaigns Campaigns { get; set; }
        public virtual Employees Employees { get; set; }
    }
}
